version: 2
jobs:
  deploy:
    steps:
      - checkout
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:4416b722-5223-49d3-892e-acef481bd7ad@git.heroku.com/practice_react.git master
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
view raw